/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as ModelPerformanceRouteImport } from './routes/model-performance'
import { Route as ModelEvaluationRouteImport } from './routes/model-evaluation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnersRouteImport } from './routes/learners'
import { Route as InterventionsRouteImport } from './routes/interventions'
import { Route as ExplainabilityRouteImport } from './routes/explainability'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnersKeyRouteImport } from './routes/learners.$key'

const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelPerformanceRoute = ModelPerformanceRouteImport.update({
  id: '/model-performance',
  path: '/model-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelEvaluationRoute = ModelEvaluationRouteImport.update({
  id: '/model-evaluation',
  path: '/model-evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnersRoute = LearnersRouteImport.update({
  id: '/learners',
  path: '/learners',
  getParentRoute: () => rootRouteImport,
} as any)
const InterventionsRoute = InterventionsRouteImport.update({
  id: '/interventions',
  path: '/interventions',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainabilityRoute = ExplainabilityRouteImport.update({
  id: '/explainability',
  path: '/explainability',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnersKeyRoute = LearnersKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => LearnersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explainability': typeof ExplainabilityRoute
  '/interventions': typeof InterventionsRoute
  '/learners': typeof LearnersRouteWithChildren
  '/login': typeof LoginRoute
  '/model-evaluation': typeof ModelEvaluationRoute
  '/model-performance': typeof ModelPerformanceRoute
  '/overview': typeof OverviewRoute
  '/learners/$key': typeof LearnersKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explainability': typeof ExplainabilityRoute
  '/interventions': typeof InterventionsRoute
  '/learners': typeof LearnersRouteWithChildren
  '/login': typeof LoginRoute
  '/model-evaluation': typeof ModelEvaluationRoute
  '/model-performance': typeof ModelPerformanceRoute
  '/overview': typeof OverviewRoute
  '/learners/$key': typeof LearnersKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explainability': typeof ExplainabilityRoute
  '/interventions': typeof InterventionsRoute
  '/learners': typeof LearnersRouteWithChildren
  '/login': typeof LoginRoute
  '/model-evaluation': typeof ModelEvaluationRoute
  '/model-performance': typeof ModelPerformanceRoute
  '/overview': typeof OverviewRoute
  '/learners/$key': typeof LearnersKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explainability'
    | '/interventions'
    | '/learners'
    | '/login'
    | '/model-evaluation'
    | '/model-performance'
    | '/overview'
    | '/learners/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explainability'
    | '/interventions'
    | '/learners'
    | '/login'
    | '/model-evaluation'
    | '/model-performance'
    | '/overview'
    | '/learners/$key'
  id:
    | '__root__'
    | '/'
    | '/explainability'
    | '/interventions'
    | '/learners'
    | '/login'
    | '/model-evaluation'
    | '/model-performance'
    | '/overview'
    | '/learners/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExplainabilityRoute: typeof ExplainabilityRoute
  InterventionsRoute: typeof InterventionsRoute
  LearnersRoute: typeof LearnersRouteWithChildren
  LoginRoute: typeof LoginRoute
  ModelEvaluationRoute: typeof ModelEvaluationRoute
  ModelPerformanceRoute: typeof ModelPerformanceRoute
  OverviewRoute: typeof OverviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-performance': {
      id: '/model-performance'
      path: '/model-performance'
      fullPath: '/model-performance'
      preLoaderRoute: typeof ModelPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-evaluation': {
      id: '/model-evaluation'
      path: '/model-evaluation'
      fullPath: '/model-evaluation'
      preLoaderRoute: typeof ModelEvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learners': {
      id: '/learners'
      path: '/learners'
      fullPath: '/learners'
      preLoaderRoute: typeof LearnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interventions': {
      id: '/interventions'
      path: '/interventions'
      fullPath: '/interventions'
      preLoaderRoute: typeof InterventionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explainability': {
      id: '/explainability'
      path: '/explainability'
      fullPath: '/explainability'
      preLoaderRoute: typeof ExplainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learners/$key': {
      id: '/learners/$key'
      path: '/$key'
      fullPath: '/learners/$key'
      preLoaderRoute: typeof LearnersKeyRouteImport
      parentRoute: typeof LearnersRoute
    }
  }
}

interface LearnersRouteChildren {
  LearnersKeyRoute: typeof LearnersKeyRoute
}

const LearnersRouteChildren: LearnersRouteChildren = {
  LearnersKeyRoute: LearnersKeyRoute,
}

const LearnersRouteWithChildren = LearnersRoute._addFileChildren(
  LearnersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExplainabilityRoute: ExplainabilityRoute,
  InterventionsRoute: InterventionsRoute,
  LearnersRoute: LearnersRouteWithChildren,
  LoginRoute: LoginRoute,
  ModelEvaluationRoute: ModelEvaluationRoute,
  ModelPerformanceRoute: ModelPerformanceRoute,
  OverviewRoute: OverviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
